
name: Upload Artifact To Release

# simple reuseable workflow to unpack and upload all artifact in dist/
on:
  workflow_call:
    inputs:
      # fixed path for now
      artifact-path:
        required: false
        type: string
        default: dist/
      # all artifact for now
      artifact-name:
        required: false
        type: string
      merge-multiple:
        required: false
        type: boolean
        default: true        
permissions:
  contents: write
  # need write to push to release artifact 

jobs:

  # this is not part of requirement
  Upload_to_release:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          path: dist/
          merge-multiple: ${{ inputs.merge-multiple }}

      - name: lsR
        run: |
          ls -R
              
      - name: Push to Release

        uses: softprops/action-gh-release@v2.0.5
        with:        
          files: dist/*
          fail_on_unmatched_files: true