
name: Python Build and Test

env:
  APP_NAME: foo
  APP_VERSION: bar

# simple git flow for single developer with linear development  
# release with tag = pyproject.toml versio = $APP_VERSION
on:
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"
  workflow_dispatch : {}

permissions:
  contents: write
  # need write to push to release artifact 

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build 

    - name: Build package
      run: python -m build

    - name: project_name
      run: | 
        echo APP_NAME=$(python -c 'import tomllib; print(tomllib.load(open("pyproject.toml", "rb"))["project"]["name"])') >> $GITHUB_ENV
        echo APP_VERSION=$(python -c 'import tomllib; print(tomllib.load(open("pyproject.toml", "rb"))["project"]["version"])') >> $GITHUB_ENV

    - name: Setup Test
      run: echo "Hello World" > expected.out

    - name: Run locally 
      run: |
        echo "Run locally"
        pip install dist/${{ env.APP_NAME }}-${{ env.APP_VERSION }}.tar.gz
        echo ==========================================
        python -m ${{ env.APP_NAME }} 
        echo ==========================================

    - name: Test locally 
      run: |
        echo "Test locally"
        python -m ${{ env.APP_NAME }} > local.test.out
        diff local.test.out expected.out

    - name: Build Docker
      run: |
        docker build . -t  ${{ env.APP_NAME }}:${{ github.sha }}  --build-arg APP_VERSION=$APP_VERSION
       
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.APP_NAME }}:${{ github.sha }} 
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'      
        
    - name: Run Docker
      run: |
        echo "Run Docker"
        echo ==========================================
        docker run -t ${{ env.APP_NAME }}:${{ github.sha }}
        echo ==========================================

    - name: Test Docker 
      run: |
        echo "Test Docker"
        docker run -t ${{ env.APP_NAME }}:${{ github.sha }} > docker.test.out
        wc -l docker.test.out expected.out
        diff docker.test.out expected.out

    - name: Upload Build Artifact
      # if push to main or create release
      if: ${{ github.ref != 'refs/heads/main' }} || ${{ github.event_name == 'workflow_dispatch'}} || ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ env.APP_NAME }}-python-module
        path: dist/*
        if-no-files-found: error
        overwrite: true

  # this is not part of requirement
  Upload_to_release:
    uses: "./.github/workflows/artifact-release.yml"
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs : BuildAndTest
