
name: Upload Release

# simple git flow for single developer with linear development  
# release with tag = pyproject.toml versio = $APP_VERSION
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch : {}

permissions:
  contents: write

  # need write to push to release artifact 

jobs:

  # this is not part of requirement
  Upload_to_release:
    runs-on: ubuntu-latest
    steps:
    # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          path: dist/
          merge-multiple: true

      - name: lsR
        run: |
          ls -R
              
      - name: Push to Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2.0.5
        with:        
          files: dist/*
          fail_on_unmatched_files: true